### PR TITLE
update to NSB v7

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/servicecontrol-maintainers so this is blocked by the use of

```
<PackageReference Include="ServiceControl.Plugin.Nsb6.Heartbeat" Version="3.0.1" />
```

Can that dependency broken? if not how do we handle it?

**Comment by WilliamBZA** [comment]
I think once we implement [this](https://github.com/Particular/DotNetCoreLaunch/issues/7#issuecomment-324560552) we should be ok with breaking this dependency

**Comment by SzymonPobiega** [comment]
the dependency is just for the tests, right? I guess we can temporarily remove it until we have V7 plugins.

**Comment by SimonCropp** [comment]
@SzymonPobiega can u do a commit that does that?

**Comment by SzymonPobiega** [comment]
Thanks @SimonCropp . I'll release a beta now.

**Comment by SimonCropp** [comment]
@SzymonPobiega awesome. thanks

**Comment by SzymonPobiega** [comment]
@SimonCropp 2.0.0-bata1 is on myget.

**Pull request merged**
