### PR TITLE
Prepare RC1

### PR DESCRIPTION
**Pull request by bording**

### CODE REVIEW

**Comment by timbussmann** [comment]
seems some tests are failing in send-only mode. Is that new? I can't seem to find builds for the release branch somehow on TC?

**Comment by bording** [comment]
Hmm, not sure what's happening here yet. I'll need to investigate.

**Comment by SzymonPobiega** [comment]
It is probably me. I'll fix it

**Comment by SzymonPobiega** [comment]
@bording the RC1 of NSB.Raw broke the send-only mode for native pub-sub transports. I've fixed that with RC2 and updated the TA to use the new RC of Raw. Should be fine now.

**Comment by timbussmann** [comment]
Seems like we can merge this now that builds are green again and @SzymonPobiega reviewed the PR.

**Pull request merged**
